Messenger/config/routes.rb
Rails.application.routes.draw do
  	
  	root 	'pages#index'

	get 	'/signup',	to: 'users#new'
	post 	'/signup',	to: 'users#create'

	get 	'/login',	to: 'sessions#new'
	post 	'/login',	to: 'sessions#create'
	delete	'/logout',	to: 'sessions#destroy'

	get 	'/broadcast', to: 'messages#broadcast' 
	post    '/broadcast', to: 'messages#create_broadcast' 
	resources :users
	resources :messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Messenger/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Messenger/app/models/message.rb
class Message < ApplicationRecord
	belongs_to :sender, :class_name => 'User'
	belongs_to :recipient, :class_name => 'User'

	validates :body, presence: true,
					 length: { maximum: 80 }
end

Messenger/app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	has_many :sent_messages, :class_name => 'Message', 
			 :foreign_key => 'sender_id'
	has_many :received_messages, :class_name => 'Message', 
			 :foreign_key => 'recipient_id'
	validates :name, presence: true,
					 length: { maximum: 40 }
	validates :email, presence: true,
					  uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, 
						 length: { minimum: 6 }

	def is_user?
		client == 1
	end

	def name_title
		@title = is_user? ? ", USER" : ", TRAINER"
		"#{name}" + @title
	end
end

Messenger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

Messenger/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :logged_in_user
	before_action :trainer_only, only: [:broadcast, :create_broadcast]

	def index
		@sent = current_user.sent_messages
		@received = current_user.received_messages
		@read, @unread = [], []
		@received.each do |recv|
			if recv.read == true
				@read << recv
			else
				@unread << recv
				recv.read = true
				recv.save
			end
		end
	end

	def new
		@message = Message.new
		@recipients = User.where.not(id: current_user.id).order(:name)
	end

	def create
		@message = Message.new(message_params)
		if @message.save
			flash[:notice] = "Message sent"
			redirect_to messages_path
		else
			flash[:error] = "Message not sent"
			redirect_to new_message_path
		end
	end

	def broadcast
		@message = Message.new
	end

	def create_broadcast
		@recipients = User.where.not(id: current_user.id).order(:name)
		@recipients.each do |r|
			@message = Message.new(broadcast_params)
			@message.recipient_id = r.id
			if @message.save
			else
				flash[:error] = "Broadcast failed"
			end
		end

		flash[:notice] = "Broadcast successful"
		redirect_to messages_path
	end

	private

		def message_params
			params.require(:message).permit(:body, :sender_id,
										 	:recipient_id)
		end

		def broadcast_params
			params.require(:message).permit(:body, :sender_id)
		end

	  	def logged_in_user
      		unless logged_in?
      			flash[:error] = "You must be logged in"
        		redirect_to login_path
      		end
    	end

    	def trainer_only
    		if current_user.is_user?
    			flash[:error] = "You must be a trainer"
    			redirect_to messages_path
    		end
    	end
    
end

Messenger/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	if logged_in?
  		@num_unread = current_user.received_messages.select { |recv| recv.read == false }.length
  	end
  end
end

Messenger/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		 user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			log_in user
			redirect_to root_path
		else
			flash.now[:error] = 'Invalid email/password'
			render 'new'
		end
	end

	def destroy
		log_out
		redirect_to root_path
	end

end

Messenger/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:show]

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		@user.client = params[:client]
		if @user.save
			log_in @user
			redirect_to root_path
		else
			flash.now[:error] = "Invalid Signup Info"
			render 'new'
		end
	end

	private

		def user_params
			params.require(:user).permit(:name, :email, :password,
										 :password_confirmation, :client)
		end

		# Checks if user is logged in
    	def logged_in_user
      		unless logged_in?
      			flash[:error] = "You must be logged in"
        		redirect_to login_path
      		end
    	end

end

Messenger/app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
end

Messenger/app/helpers/messages_helper.rb
module MessagesHelper
end

Messenger/app/helpers/pages_helper.rb
module PagesHelper
end

Messenger/app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def logged_in?
    	!current_user.nil?
  	end

end

Messenger/app/helpers/users_helper.rb
module UsersHelper
end

Messenger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messenger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div  id="main-container", class="container text-center">
    	<div class="col-md-9">
        <%= flash_messages %>
  			<%= yield %>
  		</div>
	</div>
  </body>
</html>

Messenger/app/views/messages/broadcast.html.erb
<h1> New Broadcast </h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:message, :url => broadcast_path) do |f| %>
	  <div class ="form-group">
	    <%= f.label :body, "Message" %>
	    <%= f.text_area :body, class: 'form-control' %>
	  </div>

	  <%= f.hidden_field :sender_id, :value => current_user.id %>

	  <%= f.submit "Send", class: "btn btn-primary" %>
	  <%= link_to "Back to Messages", messages_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

Messenger/app/views/messages/index.html.erb
<h1> Messages </h1>
<%= link_to "New chat", new_message_path, class: "btn btn-primary"%>
<% if !current_user.is_user? %>
  <%= link_to "Broadcast", broadcast_path, class: "btn btn-primary"%>
<% end %>
<%= link_to "Back to Home", root_path, class: "btn btn-primary"%>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-4">
    <p> Unread Messages </p>
    <% @unread.each do |ur| %>
      <div class="panel panel-danger">
        <div class="panel-heading">Sent by: <%= ur.sender.name %>, at: <%= ur.created_at %></div>
        <div class="panel-body">
          <p><%= ur.body %></p>
        </div>
      </div>
    <% end %>
    </div>

    <div class="col-md-4">
    <p> Read Messages </p>
    <% @read.each do |r| %>
      <div class="panel panel-success">
        <div class="panel-heading">Sent by: <%= r.sender.name %>, at: <%= r.created_at %></div>
        <div class="panel-body">
          <p><%= r.body %></p>
        </div>
      </div>
    <% end %>
    </div>

    <div class="col-md-4">
    <p> Sent Messages </p>
    <% @sent.each do |s| %>
      <div class="panel panel-primary">
        <div class="panel-heading">Sent to: <%= s.recipient.name %>, at: <%= s.created_at %></div>
        <div class="panel-body">
          <p><%= s.body %></p>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

Messenger/app/views/messages/new.html.erb
<h1> New Message </h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@message) do |f| %>
	  <div class ="form-group">
	    <%= f.label :body, "Message" %>
	    <%= f.text_area :body, class: 'form-control' %>
	  </div>

	  <%= f.hidden_field :sender_id, :value => current_user.id %>

	  <div class ="form-group">
	    <%= f.label :recipient_id, "Recipient" %>
	    <%= f.collection_select :recipient_id, @recipients, :id, :name, {}, {class: 'form-control'}%>
	  </div>

	  <%= f.submit "Send", class: "btn btn-primary" %>
	  <%= link_to "Back to Messages", messages_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

Messenger/app/views/pages/index.html.erb
<div class = "center jumbotron">
	<h1>Welcome to Messenger</h1>

	<h2> A simple app for exchanging messages! </h2>

	<% if logged_in? %>
		<%= link_to "Profile", user_path(current_user), class: 'btn btn-primary' %>
		<%= link_to "messages", class: 'btn btn-primary' do %>
    		Chat <%= content_tag :span, @num_unread, class: 'badge' %>
		<% end %>
		<%= link_to "Logout", logout_path, method: :delete, class: "btn btn-primary" %>
	<% else %>
		<%= link_to "Log In", login_path, class: "btn btn-lg btn-primary" %>
	<% end %>
</div>

Messenger/app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <div class ="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class ="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class ="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control'%>
      </div>  

      <div class ="form-group">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control'%>
      </div>

      <div class ="form-group">
        <%= f.label :client, "User Type" %>
        <%= select_tag(:client, options_for_select([['User', 1], ['Trainer', 2]], :selected => params[:client]), {:class => 'form-control'})%>
      </div>
      
      <%= f.submit "Create my account", class: "btn btn-primary" %>
      <%= link_to "Return to Home", root_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

Messenger/app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p> Email: <%= @user.email %></p>
<p> Client-Type: <%= (@user.client == 1) ? 'User' : 'Trainer' %></p>
<%= link_to "Back to Home",	root_path, class: "btn btn-primary" %>
<%= link_to "Logout", logout_path, method: :delete, class: "btn btn-primary" %>